### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by manishnagaraj** [manishnagaraj/WiFi-Testbed#2]
[Error] main.cpp@67,48: no matching function for call to 'WiFiInterface::get_ip_address()'
[Error] main.cpp@68,50: no matching function for call to 'WiFiInterface::get_gateway()'
[Warning] main.cpp@229,13: 'void wait(float)' is deprecated: 'wait' is deprecated in favor of explicit sleep functions. To sleep, 'wait' should be replaced by 'ThisThread::sleep_for' (C++) or 'thread_sleep_for' (C). If you wish to wait (without sleeping), call 'wait_us'. 'wait_us' is safe to call from ISR context. [since mbed-os-5.14] [-Wdeprecated-declarations]
[ERROR] In file included from ./mbed-os/mbed.h:65:0,
                 from ./src/main.cpp:1:
./mbed-os/drivers/Serial.h:61:70: warning: 'Serial' is deprecated: Use printf and puts instead to access the console, BufferedSerial for blocking applications or UnbufferedSerial if bypassing locks in IRQ or short of RAM. [since mbed-os-6.0.0] [-Wdeprecated-declarations]
     ) Serial : public SerialBase, public Stream, private NonCopyable<Serial> {
                                                                      ^~~~~~
./mbed-os/drivers/Serial.h:61:7: note: declared here
     ) Serial : public SerialBase, public Stream, private NonCopyable<Serial> {
       ^~~~~~
In file included from ./mbed-os/mbed.h:71:0,
                 from ./src/main.cpp:1:
./mbed-os/drivers/RawSerial.h:64:57: warning: 'RawSerial' is deprecated: Use UnbufferedSerial instead. [since mbed-os-6.0.0] [-Wdeprecated-declarations]
     ) RawSerial: public SerialBase, private NonCopyable<RawSerial> {
                                                         ^~~~~~~~~
./mbed-os/drivers/RawSerial.h:64:7: note: declared here
     ) RawSerial: public SerialBase, private NonCopyable<RawSerial> {
       ^~~~~~~~~
In file included from ./mbed-os/mbed.h:73:0,
                 from ./src/main.cpp:1:
./mbed-os/drivers/UARTSerial.h:55:79: warning: 'UARTSerial' is deprecated: Use BufferedSerial instead. [since mbed-os-6.0.0] [-Wdeprecated-declarations]
     ) UARTSerial : private SerialBase, public FileHandle, private NonCopyable<UARTSerial> {
                                                                               ^~~~~~~~~~
./mbed-os/drivers/UARTSerial.h:55:7: note: declared here
     ) UARTSerial : private SerialBase, public FileHandle, private NonCopyable<UARTSerial> {
       ^~~~~~~~~~
./mbed-os/drivers/UARTSerial.h:177:5: warning: 'virtual int mbed::UARTSerial::set_blocking(bool)' is deprecated: The class has been deprecated and will be removed in the future. [-Wdeprecated-declarations]
     }
     ^
./mbed-os/drivers/UARTSerial.h:173:17: note: declared here
     virtual int set_blocking(bool blocking)
                 ^~~~~~~~~~~~
./mbed-os/drivers/UARTSerial.h:188:5: warning: 'virtual bool mbed::UARTSerial::is_blocking() const' is deprecated: The class has been deprecated and will be removed in the future. [-Wdeprecated-declarations]
     }
     ^
./mbed-os/drivers/UARTSerial.h:185:18: note: declared here
     virtual bool is_blocking() const
                  ^~~~~~~~~~~
./src/main.cpp:13:21: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 #define TIER_1_IP   "192.168.43.73"
                     ^
./src/main.cpp:18:14: note: in expansion of macro 'TIER_1_IP'
 char* IP   = TIER_1_IP ;
              ^~~~~~~~~
./src/main.cpp: In function 'void print_info()':
./src/main.cpp:67:48: error: no matching function for call to 'WiFiInterface::get_ip_address()'
     printf ( "IP: %s\n", wifi->get_ip_address () ) ;
                                                ^
In file included from ./mbed-os/features/netsocket/NetworkStack.h:23:0,
                 from ./mbed-os/features/netsocket/nsapi.h:31,
                 from ./mbed-os/mbed.h:26,
                 from ./src/main.cpp:1:
./mbed-os/features/netsocket/NetworkInterface.h:111:27: note: candidate: virtual nsapi_error_t NetworkInterface::get_ip_address(SocketAddress*)
     virtual nsapi_error_t get_ip_address(SocketAddress *address);
                           ^~~~~~~~~~~~~~
./mbed-os/features/netsocket/NetworkInterface.h:111:27: note:   candidate expects 1 argument, 0 provided
./src/main.cpp:68:50: error: no matching function for call to 'WiFiInterface::get_gateway()'
     printf ( "Gateway: %s\n", wifi->get_gateway () ) ;
                                                  ^
In file included from ./mbed-os/features/netsocket/NetworkStack.h:23:0,
                 from ./mbed-os/features/netsocket/nsapi.h:31,
                 from ./mbed-os/mbed.h:26,
                 from ./src/main.cpp:1:
./mbed-os/features/netsocket/NetworkInterface.h:140:27: note: candidate: virtual nsapi_error_t NetworkInterface::get_gateway(SocketAddress*)
     virtual nsapi_error_t get_gateway(SocketAddress *address);
                           ^~~~~~~~~~~
./mbed-os/features/netsocket/NetworkInterface.h:140:27: note:   candidate expects 1 argument, 0 provided
./src/main.cpp: In function 'int main()':
./src/main.cpp:229:13: warning: 'void wait(float)' is deprecated: 'wait' is deprecated in favor of explicit sleep functions. To sleep, 'wait' should be replaced by 'ThisThread::sleep_for' (C++) or 'thread_sleep_for' (C). If you wish to wait (without sleeping), call 'wait_us'. 'wait_us' is safe to call from ISR context. [since mbed-os-5.14] [-Wdeprecated-declarations]
  wait ( 3.0 ) ;
             ^
In file included from ./mbed-os/mbed.h:90:0,
                 from ./src/main.cpp:1:
./mbed-os/platform/mbed_wait_api.h:76:6: note: declared here
 void wait(float s);
      ^~~~

[mbed] ERROR: "/usr/bin/python" returned error.
       Code: 1
       Path: "/home/manish/Downloads/WiFi-Testbed-wifi"
       Command: "/usr/bin/python -u /home/manish/Downloads/WiFi-Testbed-wifi/mbed-os/tools/make.py -t GCC_ARM -m NUCLEO_F401RE --source . --build ./BUILD/NUCLEO_F401RE/GCC_ARM"
       Tip: You could retry the last command with "-v" flag for verbose output

**Comment by adithyabhatkajake** [comment]
Delete all build files.
Run `mbed deploy` and let me know if that helps.
